version: "3.9"

services:
  web:
    build: .
    container_name: shopstack_web
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  db:
    image: postgres:16
    container_name: shopstack_db
    environment:
      POSTGRES_DB: shopstack
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: shopstack_redis
    ports:
      - "6379:6379"
